### ISSUE TITLE
MyPet v3.14.0 generated an exception while executing task 5720

### ISSUE THREAD

**Issue by Mr-Saitam** [MyPetORG/MyPet#1760]
The plugin spams this repeatedly in the console.

! [Sat 17:48:00 WARN  de.Keyle.MyPet.MyPetPlugin] [MyPet] Plugin MyPet v3.14.0 generated an exception while executing task 5720
java.lang.NullPointerException
! [Sat 17:48:00 WARN  de.Keyle.MyPet.MyPetPlugin] [MyPet] Plugin MyPet v3.14.0 generated an exception while executing task 5720
java.lang.NullPointerException
! [Sat 17:48:00 WARN  de.Keyle.MyPet.MyPetPlugin] [MyPet] Plugin MyPet v3.14.0 generated an exception while executing task 5720
java.lang.NullPointerException
! [Sat 17:48:01 WARN  de.Keyle.MyPet.MyPetPlugin] [MyPet] Plugin MyPet v3.14.0 generated an exception while executing task 5720
java.lang.NullPointerException
! [Sat 17:48:01 WARN  de.Keyle.MyPet.MyPetPlugin] [MyPet] Plugin MyPet v3.14.0 generated an exception while executing task 5720
java.lang.NullPointerException
! [Sat 17:48:01 WARN  de.Keyle.MyPet.MyPetPlugin] [MyPet] Plugin MyPet v3.14.0 generated an exception while executing task 5720
java.lang.NullPointerException

**Comment by Mr-Saitam** [comment]
[ticket.zip](https://github.com/user-attachments/files/24357028/ticket.zip)

**Comment by UserDerezzed** [comment]
It looks like an issue with player `xX_Corchito_Xx`'s Pet data. I'm looking into it now.

**Comment by UserDerezzed** [comment]
The issue has to do with the library we're using to read/write NBT data. I'm making an update to that library and then this issue should be resolved. It's possible that you'll have to restore this specific user's data, because once the server restarts, the inventory data will be wiped.

**Comment by Mr-Saitam** [comment]
> The issue has to do with the library we're using to read/write NBT data. I'm making an update to that library and then this issue should be resolved. It's possible that you'll have to restore this specific user's data, because once the server restarts, the inventory data will be wiped.

Oh, okay, thank you very much. I'll wait for the new version/build.

**Comment by UserDerezzed** [comment]
Can you confirm which version of MyPet you were using before you updated?

**Comment by Mr-Saitam** [comment]
> Can you confirm which version of MyPet you were using before you updated?

MyPet-3.14.0-b#14

**Comment by Mr-Saitam** [comment]
> After further investigation, I believe it's possible that your server had crashed and resulted in corrupted MyPet data for this user. Do you have any crash reports on your server?
> 
> Nonetheless, I am adding additional checks to MyPet to make sure that instead of spamming the console, the plugin will reset the skill data if it is found to be corrupted and output a message to the console with a backup.

This problem occurred previously. I updated to MyPet version 3.14.0-b#14, but it still occurred. To check whether it was a data issue, I deleted all MyPet configuration and users data. The error persisted after that. I have no other error logs or crash reports, only the MyPet error I mentioned. That is why I decided to report it.
